# Generated by Django 3.0.8 on 2020-07-06 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='BankBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('balance_achieve', models.IntegerField(default=0)),
                ('enable', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='TypeActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('balance_achieve', models.IntegerField(default=0)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.Bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBalanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_before', models.IntegerField(default=0)),
                ('balance_after', models.IntegerField(default=0)),
                ('activity', models.CharField(max_length=32)),
                ('ip', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=250)),
                ('user_agent', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('confirm', models.BooleanField(default=False)),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('send_to_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.Bank')),
                ('typeActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.TypeActivity')),
                ('user_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.UserBalance')),
            ],
        ),
        migrations.CreateModel(
            name='BankBalanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_before', models.IntegerField(default=0)),
                ('balance_after', models.IntegerField(default=0)),
                ('activity', models.CharField(max_length=32)),
                ('ip', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=250)),
                ('user_agent', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('bank_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.BankBalance')),
                ('typeActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.TypeActivity')),
            ],
        ),
    ]
